name: Automatic Rebase

on: [pull_request_target]

jobs:
  _:
    name: Automatic Rebase

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - uses: ljharb/rebase@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
